### PR TITLE
[FEAT] Redesign

### PR DESCRIPTION
**Pull request by kyjus25**
# Changelog

- ✨ Added mobile nav drawer
- 🎨 Converted CSS to Tailwind (drastically simplifying the styling)
- 🎨 Moved pages into "pages" folder, and partials into a "partials" folder to ease the searching fatigue
- 🎨 Replaced IDs with HTML5 elements for `header`, `article`, and `footer`
- ⚡️ Added `nodemon` and `concurrently` to improve dev experience by reloading on file changes
- 💄 Converted to `fontawesome` for smaller HTML footprint when using icons
- 💄 Highlight the active page in the navbar
- 💄 Added [Dracula](https://draculatheme.com/) theme because i'm a sucker for Dracula
- 🐛 Search input did not persist the user's input upon searching

# Important Notes

- `start` and `start:dev` commands remain the appropriate way to start the application.
- `site.css` has been moved to the `src` directory. Tailwind will build it to the `public` directory on start.

# Showcase

| Default      | GitHub Dark | Dracula |
| ----------- | ----------- | ----------- |
|       |        |        |

| Sign Up      | User |
| ----------- | ----------- |
|       |         |

### CODE REVIEW

**Comment by confused-Techie** [comment]
So while this redesign truly looks amazing, and sounds like it'll make the dev experience significantly better, I may take some time reviewing this one just to make sure everything still works as expected, (Especially since no kind of proper testing has been implemented on this repo yet).

I just wanted to check in to see, was this the sorta thing you were hoping to see before a release? If so I can try to rush faster on it, but otherwise if we are fine having it a day or two afterwards then that sounds fine by me.

But otherwise seriously fantastic work

**Comment by kyjus25** [comment]
I think it looks worse than it is because the file paths changed. The handlers themselves should be unchanged for this PR

**Comment by kyjus25** [comment]
@confused-Techie Latest auth changes have been merged to this branch, it has feature parity with prod.

#21 has been closed now that auth is definitive

**Comment by confused-Techie** [comment]
@kyjus25 for your last point, we could add an or `localhost:8080/users` although that would force people to use `8080` while in dev mode. Not sure if there's a good way to give the site's JS the port. 

While we could pass it like we do the `timecop` object, it seems unhelpful to do when running in production.

If you think we will need to do more of this in the future, maybe we could have an optional object passed into each page that includes some env vars, like `PULSAR_STATUS` and the port object? Then just disable passing that when in prod, what do you think?

**Comment by kyjus25** [comment]
@confused-Techie Easiest solution would probably be to just change it to `if (window.location.pathname === '/users')` if you are ok with that? Just use pathname instead of href

**Comment by confused-Techie** [comment]
> @confused-Techie Easiest solution would probably be to just change it to `if (window.location.pathname === '/users')` if you are ok with that? Just use pathname instead of href

Oh super cool, wasn't familiar with such an easy way to get the path. That sounds perfect, lets use it! Great call

**Comment by kyjus25** [comment]
@confused-Techie Done!

**Review by confused-Techie — CHANGES_REQUESTED** [review]
This honestly looks fantastic!

Love the attention taken to make sure the time displays nicely, as well as all existing themes still work without issue.

The dev experience is much much better here than it was previously, seeing realtime updates.

Overall love it!

The only issue I've found, and things we will need to fix before merging and rather simple.

1) But when this is pushed out to the cloud no devDepenencies are installed, meaning the whole tailwind portion will fail. So we need tailwind to be a regular dependency since the production start script uses it.

**Comment by kyjus25** [comment]
@confused-Techie Updated! Good catch

**Review by confused-Techie — APPROVED** [review]
Alright, as this isn't getting any more reviews or issues, looks like we are good to merge then.

Thanks a ton for your contribution! And this will surely make the site feel significantly more updated.

I'll take some time before pushing this out to prod

**Pull request merged**
