### PR TITLE
Clean up code blocks in READMEs

### PR DESCRIPTION
**Pull request by savetheclocktower**
I just noticed @confused-Techie did a version of this as part of #79, but I was already done with this and I thought I'd just toss it out here and see what people think. This is a follow-up to #78, which I filed a few days ago.

This PR:
* removes syntax highlighting for inline `code` elements _and_ for fenced backticks that do not declare a language. (The `auto` flag means that highlightjs will guess at the language — and often guess wrongly. GitHub doesn't guess at the language when rendering these READMEs, so I don't think we ought to guess either.)
* Removes the backticks that `@tailwindcss/typography` inexplicably puts around inline `code` elements.
* Tries to resolve the style conflicts between highlightjs and `@tailwindcss/typography` by putting the former in control. The strange bezel-looking thing around `pre` blocks happens because `@tailwindcss/typography` wants them to be black, but highlightjs wants them to be white:

Screen Shot 2023-02-24 at 2 33 51 PM

To fix this, I removed the bezel altogether and replaced it with a subtle `var(--secondary)` border:

Screen Shot 2023-02-24 at 2 36 03 PM

This approach seems to work quite well in each of our four themes.

Hey, here's a thought: at a certain point we'll be undoing so many of `@tailwindcss/typography`'s defaults that we could broach the idea of getting rid of it altogether. But that's a topic for another time.

### CODE REVIEW

**Comment by confused-Techie** [comment]
Thanks for this! I'll take some time to review it and test it out.

And honestly hopefully we can get our two PRs to work together, since personally I love the style used for inline code blocks over on mine, but absolutely love getting rid of the borders here.

As for the `@tailwindcss/typography` I'm not to attached to it personally. We would just need to make sure we don't have any bad regressions, but I wouldn't be opposed to seeing a PR addressing it, if we ever wanted to tackle it.

But as always thanks for this!

**Comment by savetheclocktower** [comment]
Just promise me we can get rid of the backticks, OK? 😟

**Comment by confused-Techie** [comment]
> Just promise me we can get rid of the backticks, OK? 😟

Aha of course, we can get rid of them on the code blocks. Do you mind them on the inline code as well?

**Comment by savetheclocktower** [comment]
They're only present on the inline code right now. I don't understand the goal of the person who had that idea. I put backticks around something because that's how you indicate a `code` element in Markdown — not because I want _actual backticks_ around it in the generated text.

**Comment by confused-Techie** [comment]
> They're only present on the inline code right now. I don't understand the goal of the person who had that idea. I put backticks around something because that's how you indicate a `code` element in Markdown — not because I want _actual backticks_ around it in the generated text.

Ahh yeah good point, for some reason I remembered them appearing elsewhere as well.

But yeah lets get rid of them, doesn't make much sense for them to be there.

**Comment by confused-Techie** [comment]
So I'm wanting to get this and my PR of the same theme both merged in, but wanted to check in, is there a specific reason we needed to add some of the CSS to the `tailwind.config.js` rather than to the `site.css`?

If that's because the tailwind data is parsed first and adds content (```) before we can remove it then that makes sense. Although mostly I'd like to try to keep configurations all in one place if we can help it. Otherwise if that's what we need to do to remove the backticks and restore theming control to highlight-js then that makes sense.

**Comment by savetheclocktower** [comment]
My thinking was that it made more sense to tell Tailwind not to apply some of the styles in the first place instead of trying to undo them bit-by-bit with overriding CSS.

**Comment by confused-Techie** [comment]
> My thinking was that it made more sense to tell Tailwind not to apply some of the styles in the first place instead of trying to undo them bit-by-bit with overriding CSS.

Yeah fair enough that makes sense. Just wanting to make sure there was good cause for it, thanks!

**Review by confused-Techie — APPROVED** [review]
Alright, @savetheclocktower if you wouldn't mind one last check. 

I've merged me other PR, and just waiting on this one to update production. I've resolved the conflicts here, simply by using your CSS selector instead of mine, but placing my CSS declarations within it. Since they largely accomplished the same thing, but like mentioned earlier I was hoping to keep that styling and you didn't seem concerned.

So if that all looks good lets go ahead and merge this one! Thanks again for the work

**Comment by savetheclocktower** [comment]
Looks great. 👍

**Pull request merged**
