### PR TITLE
Adds `timecop` capabilities

### PR DESCRIPTION
**Pull request by confused-Techie**
This PR adds a new feature to the website called `timecop`, the naming borrowed from the internal `timecop` tool of the Pulsar Editor.

As we continue to investigate what causes long loading times of the website, `timecop` allows end users and us to investigate what takes the time of our page loads. 

Once a page is loaded within the browsers DevTools Console a user can run `loadStats()` and get some output of the page load times internally, such as how long API Requests took, and how long it took to transcribe JSON data, or the time taken to check Local/Remote Caches for data.

Ideally this can be used in future debugging and issue templates.

### CODE REVIEW

**Review by DeeDeeG — APPROVED** [review]
Sounds like a good idea!

And the code looks like it should work (I haven't tested it or looked it over way way closely, though.)

**Comment by DeeDeeG** [comment]
Is there a way to run this repo locally and test? Not sure if I have time at the moment, but I could do more insightful reviews if I can run this locally and test.

**Comment by confused-Techie** [comment]
> Is there a way to run this repo locally and test? Not sure if I have time at the moment, but I could do more insightful reviews if I can run this locally and test.

That is a great point of what should be added to the readme. Thanks for pointing that out.

But yes, cloning the repo and then changing the `app.example.yaml` to `app.yaml` and changing values as needed would be the best way to get setup.

Then just run:

```shell
npm install
npm start
```

The only issue, is with Caching now present on some endpoints, you'd need a key file for Google Cloud. But without it, I don't think the logic is currently robust enough to fail gracefully on that. So you can test all endpoints except the homepage and the featured page without a Google Key file. But I'll work on making that fail more gracefully, and adding this as documentation to the readme.

**Comment by DeeDeeG** [comment]
I got an error in the console when testing this.

`performance` is undefined in utils.js.

In Node, you don't get `performance.now` out of the box, you have to `require()` the built-in NodeJS module `perf_hooks` -- for example, I think this works: `const perfNow = require(perf_hooks).performance.now`.

**Comment by confused-Techie** [comment]
> I got an error in the console when testing this.
> 
> `performance` is undefined in utils.js.
> 
> In Node, you don't get `performance.now` out of the box, you have to `require()` the built-in NodeJS module `perf_hooks` -- for example, I think this works: `const perfNow = require(perf_hooks).performance.now`.

How strange. It runs fine for me locally, and I've never imported it. Maybe I've done so globally somewhere. What node version are you running? I'm currently using `v16.16.0` and doesn't error out on me.

But lemme double check if it's something strange about my setup

**Comment by confused-Techie** [comment]
But @DeeDeeG great catch, the docs say to import it, so not sure what's going on for me locally. I'll fix that, and might as well add some better docs for testing locally. Thanks for the review

**Comment by confused-Techie** [comment]
@DeeDeeG I've imported `performance` now to avoid that issue, as well as added to the readme about running locally, and finally graceful failover on the cache check. 

Let me know what you think

**Comment by DeeDeeG** [comment]
> What node version are you running?

Ah, yeah that's what happened. I was running Node 14.21.0.

I went and checked in the Node REPL (just run `node` with no arguments), and `performance.now()` just works in Node 16, 18, and 19.

I am on the oldest still supported Node LTS version when working on Atom/Pulsar stuff just out of habit.

And sorry to review and run, something came up just after I posted that, otherwise I would normally try to be available to discuss after dropping a feedback/bug report like that.

**Comment by DeeDeeG** [comment]
It's working for me now, even in Node 14.

(If interested, here are the stats I got for four different loads of the homepage:)

<details><summary>Results of running <code>loadStats()</code> (click to expand):</summary>

```
# Homepage first load
"api-request": Object { start: 14440.298506006598, end: 15273.758766010404, duration: 833.4602600038052 }
"cache-check": Object { start: 14425.71021001041, end: 14440.278861999512, duration: 14.568651989102364 }
"transcribe-json": Object { start: 15273.776468008757, end: 15308.273320004344, duration: 34.49685199558735 }

# Homepage second load
"api-request": Object { start: 72477.78414100409, end: 72849.33520500362, duration: 371.55106399953365 }
"cache-check": Object { start: 72476.31645300984, end: 72477.76896899939, duration: 1.4525159895420074 }
"transcribe-json": Object { start: 72849.34548701346, end: 72849.43485701084, duration: 0.089369997382164 }

# Homepage third load
"api-request": Object { start: 96882.3084140122, end: 97174.9148170054, duration: 292.6064029932022 }
"cache-check": Object { start: 96880.68780300021, end: 96882.292535007, duration: 1.6047320067882538 }
"transcribe-json": Object { start: 97174.92774000764, end: 97175.02171200514, duration: 0.09397199749946594 }

# Homepage fourth load
"api-request": Object { start: 116161.9091270119, end: 116463.57698400319, duration: 301.66785699129105 }
"cache-check": Object { start: 116160.22918400168, end: 116161.89091101289, duration: 1.6617270112037659 }
"transcribe-json": Object { start: 116463.58886000514, end: 116463.6777010113, duration: 0.08884100615978241 }
```

</details>

<details><summary>Same results, but tab-aligned for easy comparison (click to expand):</summary>

```
# Homepage first load
"api-request":		Object { start: 14440.298506006598,	end: 15273.758766010404,	duration: 833.4602600038052 }
"cache-check":		Object { start: 14425.71021001041,	end: 14440.278861999512,	duration: 14.568651989102364 }
"transcribe-json":	Object { start: 15273.776468008757,	end: 15308.273320004344,	duration: 34.49685199558735 }

# Homepage second load
"api-request":		Object { start: 72477.78414100409,	end: 72849.33520500362,		duration: 371.55106399953365 }
"cache-check":		Object { start: 72476.31645300984,	end: 72477.76896899939,		duration: 1.4525159895420074 }
"transcribe-json":	Object { start: 72849.34548701346,	end: 72849.43485701084,		duration: 0.089369997382164 }

# Homepage third load
"api-request":		Object { start: 96882.3084140122,	end: 97174.9148170054,		duration: 292.6064029932022 }
"cache-check":		Object { start: 96880.68780300021,	end: 96882.292535007,		duration: 1.6047320067882538 }
"transcribe-json":	Object { start: 97174.92774000764,	end: 97175.02171200514,		duration: 0.09397199749946594 }

# Homepage fourth load
"api-request":		Object { start: 116161.9091270119,	end: 116463.57698400319,	duration: 301.66785699129105 }
"cache-check":		Object { start: 116160.22918400168,	end: 116161.89091101289,	duration: 1.6617270112037659 }
"transcribe-json":	Object { start: 116463.58886000514,	end: 116463.6777010113,		duration: 0.08884100615978241 }
```

</details>

Please note this is on an HDD, and a fairly old machine in general (so if RAM speed is a factor, then that. Also, this is an older generation of RAM, less new/advanced CPU instructions supported...), but with a decently strong CPU for that era.

**Comment by DeeDeeG** [comment]
Thanks @Spiker985. I am just a bit out of touch with Pulsar's new build process + build dependency situation. I have to spend some time and get acquainted with that in general. I know Mauricio is tending toward newer Node with that.

Not to get too off-topic, but I tend use [`n`](https://github.com/tj/n) on Linux, because it's a really simple tool and I like how it works. I can use newer Node if that's what's required for a given project. I use [`nvs`](https://github.com/jasongin/nvs) on Windows for similar reasons.

**Comment by confused-Techie** [comment]
@DeeDeeG Good to see it wasn't something super weird on my local environment. But thanks for getting back to me, and no worries, we all have lives going on.

I appreciate the results you are getting being put here, and helps to know what's going on for others. Especially considering you can't access the remote cache the faster load speeds are all with the local caching on the homepage, which it's awesome to see how much it cuts down on load times.

But still I hope we can improve those further. But we will see.

But considering that this works just fine for you and me on the Node version we target for this `v16` as per [`app.yaml`](https://github.com/pulsar-edit/package-frontend/blob/main/app.example.yaml) I'll go ahead and move the changes to import it and merge this one.

Thanks again for everyone that's taken a look

**Pull request merged**
